pipeline {
    // This is a pre build section
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    
    // This is a build section.
    stages {
        stage('Init') {
            steps {
                script {
                     sh """
                        terraform init
                     """

                }
                
            }
        }
        stage('Plan') {
            steps {
                script { 
                     sh """
                        terraform plan

                     """
                }
             
            }
        }
        stage('Deploy') {
            input {
                message "should we continue?"
                ok "Yes, we should"
                submitter "alice,bob"
                parameters {
                    
                }
            }
            when {
                expression { "$params.DEPLOY" == "true" }
            }
            steps {
                script {
                    sh """
                        terraform apply -auto-approve
                    """

                }
                
            }
        }

    }

    post {
        always {
            echo 'I will always say hello again!'
            cleanWs()
        }

        success {
            echo 'I will run if success'
        }
       
       failure {
           echo 'I will run if failure'
       }
       aborted {
            echo 'pipeline is aborted'
       }
    }
}