pipeline {
    // This is a pre build section
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    
    // This is a build section.
    stages {
        stage('Init') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """  
                             cd 30-sg-rules
                             terraform init
                        """
                    }
                }
                
            }
        }
        stage('Plan') {
            steps {
                script { 
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                     sh """
                        cd 30-sg-rules
                        terraform plan

                     """
                }
             
            }
        }
        }
        stage('Deploy') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                    sh """
                        cd 30-sg-rules
                        terraform apply -auto-approve
                    """
                    }
                }
                
            }
        }
    }

    post {
        always {
            echo 'I will always say hello again!'
            cleanWs()
        }

        success {
            echo 'I will run if success'
        }
       
       failure {
           echo 'I will run if failure'
       }
       aborted {
            echo 'pipeline is aborted'
       }
    }
}